export const PLAYERS = [
  {
    name: "Bukayo Saka",
    team: "Arsenal",
    position: "MID",
    form: 7.5,
    price: 9.5,
    totalPoints: 120,
    ownership: 55,
    image: require("../assests/images/players/bukayo.png"),
  },
  {
    name: "Mohamed Salah",
    team: "Liverpool",
    position: "MID",
    form: 8.5,
    price: 12.5,
    totalPoints: 180,
    ownership: 85,
    image: require("../assests/images/players/salah.png"),
  },
  {
    name: "Son Heung-min",
    team: "Tottenham",
    position: "FWD",
    form: 9.5,
    price: 11.5,
    totalPoints: 200,
    ownership: 90,
    image: require("../assests/images/players/son.png"),
  },
  {
    name: "Kevin De Bruyne",
    team: "Manchester City",
    position: "MID",
    form: 8.0,
    price: 11.0,
    totalPoints: 190,
    ownership: 80,
    image: require("../assests/images/players/kdb.png"),
  },
];
