name: Trigger auto deployment for container-app-doqpmuuzbeeby

# When this action will be executed
on:
  # Automatically trigger it when detected changes in repo
  push:
    branches: 
      [ master ]
    paths:
    - 'backend/**'
    - '.github/workflows/container-app-doqpmuuzbeeby-AutoDeployTrigger-6ed3e89d-b60e-489d-82d3-65431702a54c.yml'

  # Allow manual trigger 
  workflow_dispatch:      

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions: 
      id-token: write #This is required for requesting the OIDC JWT Token
      contents: read #Required when GH token is used to authenticate with private repo

    steps:
      - name: Checkout to the branch
        uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.CONTAINERAPPDOQPMUUZBEEBY_AZURE_CLIENT_ID }}
          tenant-id: ${{ secrets.CONTAINERAPPDOQPMUUZBEEBY_AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.CONTAINERAPPDOQPMUUZBEEBY_AZURE_SUBSCRIPTION_ID }}

      - name: Build and push container image to registry
        uses: azure/container-apps-deploy-action@v2
        with:
          appSourcePath: ${{ github.workspace }}/backend 
          registryUrl: 
          registryUsername: ${{ secrets.CONTAINERAPPDOQPMUUZBEEBY_REGISTRY_USERNAME }}
          registryPassword: ${{ secrets.CONTAINERAPPDOQPMUUZBEEBY_REGISTRY_PASSWORD }}
          containerAppName: container-app-doqpmuuzbeeby
          resourceGroup: fanatsymanager9ab2
          imageToBuild: default/[parameters('containerAppName')]:${{ github.sha }}
          _buildArgumentsKey_: |
            _buildArgumentsValues_


